name: next js build with caching & artifacts

on:
 push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node Js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: build next Js app
        run:  npm run build

      - name: upload build on Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: nextJs-build
          path: dist/
        
      
          
